apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: miqbalnawawi/frontend3:latest
          ports:
            - containerPort: 3000
              name: http-port
  selector:
    matchLabels:
      app: client
